local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("VR7Hubs | POP IT TRADING ", "BloodTheme")


local Tab = Window:NewTab("اغراض اوتو شراء بفلوس ")


local Section = Tab:NewSection("اوتو شراء offsale items")

Section:NewToggle("اوتو شراء Harambe", "Auto harambe", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Harambe" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Egg", "Auto egg", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Egg" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء sanic", "Auto sanic", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Sanic" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Lem", "Auto Lem", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Lem" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Air", "Auto air", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Air" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Noob", "Auto Noob", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Noob" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Box Toy", "Auto Box Toy", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy Box Toy" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Buy Box Toy House", "Auto House", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy  House" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء box toy", "Auto box toy", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy " } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء sandman", "Auto sandman", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Box Toy SandMan" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Rainbow Star", "Auto Rainbow Star", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Rainbow Star" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle(" اوتو شراء Gold Coin", "Auto Gold Coin", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Gold Coin" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle(" اوتو شراء Helloshi", "Auto Helloshi", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Helloshi" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle(" اوتو شراء Luisi", "Auto Luisi", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Luisi" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Markio", "Auto Markio", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Markio" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Omb Bomb", "Auto Omb Bomb", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Omb Bomb" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Lil Hacker", "Auto Lil Dude", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Lil Dude" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Lil Dude", "Auto Lil Dude Real", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Lil Dude Real" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Lightstick", "Auto Heart Lightstick", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Lightstick" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Headphones", "Auto Heart Headphones", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Headphones" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Radio", "Auto Heart Radio", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Radio" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Light", "Auto Heart Light", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Light" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Gift", "Auto Heart Gift", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Gift" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Potion", "Auto Heart Potion", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Potion" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Heart Cake", "Auto Heart Cake", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Heart Cake" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hello Scary", "Auto Hello Scary", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hello Scary" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hello Snow", "Auto Hello Snow", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hello Snow" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)Section:NewToggle("Auto buy Hand Yellow", "Auto Hand Yellow", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Yellow" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Green", "Auto Hand Green", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Green" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Blue", "Auto Hand Blue", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Blue" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Purple", "Auto Hand Purple", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Purple" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Orange", "Auto Hand Orange", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Orange" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Red", "Auto Hand Red", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Red" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand White", "Auto Hand White", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand White" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Black", "Auto Hand Black", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Black" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Hand Rainbow", "Auto Hand Rainbow", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Hand Rainbow" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

local Tab = Window:NewTab("اوتو شراء الحروف")


local Section = Tab:NewSection("اوتو شراء الحروف")

Section:NewToggle("اوتو شراء F", "Auto F", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "F" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء A", "Auto A", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "A" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء B", "Auto B", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "B" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء C", "Auto C", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "C" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء D", "Auto D", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "D" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء E", "Auto E", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "E" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء F", "Auto F", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "F" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

local Tab = Window:NewTab("اوتو شراء  اشياء بفلوس")


local Section = Tab:NewSection("اوتو شراء items")

Section:NewToggle("اوتو شراء tweet", "Auto Tweet", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Tweet" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Inxta", "Auto Inxta", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Inxta" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء playbutton", "Auto Playbutton", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Silver" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Tix Tox", "Auto Tix Tox", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Tix Tox" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء  Xox controller", "Auto Xox controller", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "XOX Controller" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

local Tab = Window:NewTab("اوتو شراء اغراض ليست للبيع")


local Section = Tab:NewSection("by VR7")

Section:NewToggle("اوتو شراء demogorgan", "Auto demogorgan", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Demogorgan" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء Kawaii", "Auto Kawaii", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Demogorgan Kawaii" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء dart", "Auto dart", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Dart" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء walky talky", "Auto walky talky", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Walky Talky" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء retro bike", "Auto retro bike", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Retro Bike" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)

Section:NewToggle("اوتو شراء green ooze", "Auto green ooze", function(state) if state then _G.on = true while _G.on do wait() local args = { [1] = "Green Ooze" } game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args)) end else _G.on = false end end)


local Tab = Window:NewTab("السكربتات")


local Section = Tab:NewSection("السكربتات")

Section:NewButton("رمي اغراض كذبي ", "fake drop scam", function()
   local plr = game.Players.LocalPlayer

local chr = plr.Character

chr.RightHand:Destroy()

end)  Section:NewButton("ريسيت(reset)", "Resets Fake Drop.", function()

local plr = game.Players.LocalPlayer

local chr = plr.Character

chr.Head:Destroy()
end)

Section:NewButton("سعر التريد كشف", "Turns On XRAY For Free", function()

    game.Players.localPlayer.XRay.Value = true

end)

Section:NewButton("سكربت كيبورد", "drop peoples item .", function()
--[[
    script by Stan#8292
]]
getgenv().bind = "F" --keybind to delete popits near you
getgenv().invis = false --turns you invis so people cant see you deleting their stuff (resetting will uninvis you)
getgenv().on = true --setting this to false will stop the script
getgenv().IgnoredList = { --ignored people (script won't delete popits from these people)
    "Person1",
    "Person2",
    "Person3"
}

local domain = "paste.ee"
loadstring(game:HttpGet("https://"..domain.."/r/WFYpr/0"))()

loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)

local Tab = Window:NewTab("الحقوق")

local Section = Tab:NewSection("VR7 تم صنع السكربت من قبل ")
Section:NewButton("نسخ رابط سيرفر الديسكورد", "Drop Dart", function()
setclipboard("https://discord.gg/XafjTNQg")
            print("link copied to clipoard")
end)

Section:NewButton("نسخ اسم قناتي اليوتيوب", "Drop Dart", function()
setclipboard("VR7")
            print("link copied to clipoard")
end)
